
development:
  paypal_host: https://www.sandbox.paypal.com/
  app_host: http://4ad215b8.ngrok.io
  edmunds_key: cpes64w9wyy4yd8anrvqz74t
  edmunds_secret: 9dNGubKWMfCG8V6Yjk7rSRRw
production:
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://ffap-itt-2015.herokuapp.com
  edmunds_key: cpes64w9wyy4yd8anrvqz74t
  edmunds_secret: 9dNGubKWMfCG8V6Yjk7rSRRw
