
development:
  paypal_host: https://www.sandbox.paypal.com/
  app_host: http://4ad215b8.ngrok.io
  edmunds_key: cpes64w9wyy4yd8anrvqz74t
  edmunds_secret: 9dNGubKWMfCG8V6Yjk7rSRRw
  gmail_key: AIzaSyDXJjsPFb4mTPJxeqSwGrfhSEmo1KPGT8o
  sendgrid_username: ffap-itt-web2
  sendgrid_password: rubyonrails123
  secret_key_base: c1319cb9c09baa5300fb8a13c6be6434a134bea34f66fb6455da305e64cd91cf83f601dc3f0a487772a011497b0f6a09e725f7699c3f796784aca2b980e9c77b

production:
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://ffap-itt-2015.herokuapp.com
  edmunds_key: cpes64w9wyy4yd8anrvqz74t
  edmunds_secret: 9dNGubKWMfCG8V6Yjk7rSRRw
  gmail_key: AIzaSyDXJjsPFb4mTPJxeqSwGrfhSEmo1KPGT8o
  sendgrid_username: ffap-itt-web2
  sendgrid_password: rubyonrails123
  secret_key_base: c1319cb9c09baa5300fb8a13c6be6434a134bea34f66fb6455da305e64cd91cf83f601dc3f0a487772a011497b0f6a09e725f7699c3f796784aca2b980e9c77b
