
development:
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://469e9680.ngrok.io
production:
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://ffap-itt-2015.herokuapp.com/
