
development:
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://4169a73c.ngrok.com
production:
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://ffap-itt-2015.herokuapp.com/
