require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NegociosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Negocio. As you add validations to Negocio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NegociosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all negocios as @negocios" do
      negocio = Negocio.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:negocios)).to eq([negocio])
    end
  end

  describe "GET #show" do
    it "assigns the requested negocio as @negocio" do
      negocio = Negocio.create! valid_attributes
      get :show, {:id => negocio.to_param}, valid_session
      expect(assigns(:negocio)).to eq(negocio)
    end
  end

  describe "GET #new" do
    it "assigns a new negocio as @negocio" do
      get :new, {}, valid_session
      expect(assigns(:negocio)).to be_a_new(Negocio)
    end
  end

  describe "GET #edit" do
    it "assigns the requested negocio as @negocio" do
      negocio = Negocio.create! valid_attributes
      get :edit, {:id => negocio.to_param}, valid_session
      expect(assigns(:negocio)).to eq(negocio)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Negocio" do
        expect {
          post :create, {:negocio => valid_attributes}, valid_session
        }.to change(Negocio, :count).by(1)
      end

      it "assigns a newly created negocio as @negocio" do
        post :create, {:negocio => valid_attributes}, valid_session
        expect(assigns(:negocio)).to be_a(Negocio)
        expect(assigns(:negocio)).to be_persisted
      end

      it "redirects to the created negocio" do
        post :create, {:negocio => valid_attributes}, valid_session
        expect(response).to redirect_to(Negocio.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved negocio as @negocio" do
        post :create, {:negocio => invalid_attributes}, valid_session
        expect(assigns(:negocio)).to be_a_new(Negocio)
      end

      it "re-renders the 'new' template" do
        post :create, {:negocio => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested negocio" do
        negocio = Negocio.create! valid_attributes
        put :update, {:id => negocio.to_param, :negocio => new_attributes}, valid_session
        negocio.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested negocio as @negocio" do
        negocio = Negocio.create! valid_attributes
        put :update, {:id => negocio.to_param, :negocio => valid_attributes}, valid_session
        expect(assigns(:negocio)).to eq(negocio)
      end

      it "redirects to the negocio" do
        negocio = Negocio.create! valid_attributes
        put :update, {:id => negocio.to_param, :negocio => valid_attributes}, valid_session
        expect(response).to redirect_to(negocio)
      end
    end

    context "with invalid params" do
      it "assigns the negocio as @negocio" do
        negocio = Negocio.create! valid_attributes
        put :update, {:id => negocio.to_param, :negocio => invalid_attributes}, valid_session
        expect(assigns(:negocio)).to eq(negocio)
      end

      it "re-renders the 'edit' template" do
        negocio = Negocio.create! valid_attributes
        put :update, {:id => negocio.to_param, :negocio => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested negocio" do
      negocio = Negocio.create! valid_attributes
      expect {
        delete :destroy, {:id => negocio.to_param}, valid_session
      }.to change(Negocio, :count).by(-1)
    end

    it "redirects to the negocios list" do
      negocio = Negocio.create! valid_attributes
      delete :destroy, {:id => negocio.to_param}, valid_session
      expect(response).to redirect_to(negocios_url)
    end
  end

end
